/* 교과서 실험 — 교과서 탐구를 시뮬레이션으로 해 보고 하나만 바꿔 내 탐구로. 엔진: ../assets/inquiry.js
   교과서 쪽 번호는 비상교육 교과서. 내용은 교과서 문장을 옮기지 않고 짧게 줄여 새로 썼다. */
window.sthInquiry({ mount: "inq", key: "inq", result: "rInq", items: [
  { id: "e1", book: "과학의 역사와 문화", page: 108, title: "내진·제진·면진 설계 실험", purpose: "빨대 건물 모형에 내진·제진·면진 방식을 적용해 흔들릴 때 진동이 줄어드는지 비교한다.",
    steps: ["키트로 똑같은 구조물을 여러 개 만든다", "구조물마다 보강재·꼭대기 추·바닥 구슬 같은 다른 방식을 적용한다", "쟁반을 같은 방식으로 흔든다", "흔들림을 관찰하거나 스마트폰 가속도 앱으로 재어 비교한다", "가장 효과적인 방식을 정리한다"],
    iv: "설계 방식(없음·내진·제진·면진)", dv: "꼭대기 흔들림(가속도 m/s²)", cv: ["쟁반 흔드는 세기·빠르기", "구조물 크기·재료", "같은 쟁반"], safety: "쇠구슬이 굴러 떨어져 밟히지 않게 테두리 있는 쟁반을 쓴다.",
    extend: ["흔드는 진동수만 바꾸면 어느 방식이 어느 진동에 강할까", "층수만 바꾸면 같은 방식의 효과가 어떻게 달라질까", "흔드는 폭만 키우면 방식 사이 순서가 그대로일까"],
    sim: { kind: "model", name: "가상 흔들림 쟁반", noise: 0.03,
      note: "쟁반이 x = A·sin(2πft)로 흔들릴 때 건물을 질량-용수철-감쇠 진동자로 계산합니다. 한 층 50 g, 1층 건물의 고유 진동수 4 Hz(층수 n이면 4/n Hz), 감쇠비 8 %. 내진 = 기둥·보강재로 강성 4배. 제진 = 건물 질량 10 %인 꼭대기 추를 건물 진동수에 맞춤(덴 하르토흐 최적 조건). 면진 = 건물 질량 절반인 바닥판을 구슬 위에 올려 고유 진동수 0.7 Hz, 감쇠비 15 %로 봄. 정상 상태 값이며, 선형 모형이라 흔들림이 아주 크면 실제 모형은 그 전에 무너질 수 있습니다.",
      choices: [{ k: "ds", label: "설계 방식", opts: [["없음", 0], ["내진(보강재)", 1], ["제진(꼭대기 추)", 2], ["면진(바닥 구슬)", 3]], value: 0 }],
      inputs: [{ k: "f", label: "흔드는 진동수", unit: "Hz", min: 0.5, max: 6, step: 0.1, value: 2 },
               { k: "A", label: "흔드는 폭", unit: "mm", min: 5, max: 20, step: 1, value: 10 },
               { k: "n", label: "층수", unit: "층", min: 1, max: 5, step: 1, value: 2 }],
      outputs: [{ k: "acc", label: "꼭대기 최대 가속도", unit: "m/s²", dp: 2, expr: "(function(){var w=2*Math.PI*f,Y=A/1000,m=0.05*n,fn=4/n,k=m*Math.pow(2*Math.PI*fn,2),c=2*0.08*Math.sqrt(k*m);function C(a,b){return [a,b];}function ad(a,b){return [a[0]+b[0],a[1]+b[1]];}function sb(a,b){return [a[0]-b[0],a[1]-b[1]];}function mu(a,b){return [a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]];}function dv(a,b){var q=b[0]*b[0]+b[1]*b[1];return [(a[0]*b[0]+a[1]*b[1])/q,(a[1]*b[0]-a[0]*b[1])/q];}function ab(a){return Math.sqrt(a[0]*a[0]+a[1]*a[1]);}function two(Ma,Ka,Mb,Kb){var T=sb(Kb,C(w*w*Mb,0)),D=sb(ad(Ka,Kb),ad(C(w*w*Ma,0),dv(mu(Kb,Kb),T))),Xa=dv(mu(Ka,C(Y,0)),D);return [Xa,dv(mu(Kb,Xa),T)];}var top,base=C(Y,0);if(ds<2){var kk=ds==1?4*k:k,cc=ds==1?2*c:c,K=C(kk,w*cc);top=dv(mu(K,C(Y,0)),sb(K,C(w*w*m,0)));}else if(ds==2){var mu2=0.1,m2=mu2*m,f2=fn/(1+mu2),z2=Math.sqrt(3*mu2/(8*Math.pow(1+mu2,3))),k2=m2*Math.pow(2*Math.PI*f2,2),c2=2*z2*Math.sqrt(k2*m2);top=two(m,C(k,w*c),m2,C(k2,w*c2))[0];}else{var mb=0.5*m,kb=(m+mb)*Math.pow(2*Math.PI*0.7,2),cb=2*0.15*Math.sqrt(kb*(m+mb)),r=two(mb,C(kb,w*cb),m,C(k,w*c));top=r[1];base=r[0];}return w*w*ab(top);})()" },
                { k: "drift", label: "기둥이 휘는 폭(꼭대기−바닥판)", unit: "mm", dp: 2, expr: "(function(){var w=2*Math.PI*f,Y=A/1000,m=0.05*n,fn=4/n,k=m*Math.pow(2*Math.PI*fn,2),c=2*0.08*Math.sqrt(k*m);function C(a,b){return [a,b];}function ad(a,b){return [a[0]+b[0],a[1]+b[1]];}function sb(a,b){return [a[0]-b[0],a[1]-b[1]];}function mu(a,b){return [a[0]*b[0]-a[1]*b[1],a[0]*b[1]+a[1]*b[0]];}function dv(a,b){var q=b[0]*b[0]+b[1]*b[1];return [(a[0]*b[0]+a[1]*b[1])/q,(a[1]*b[0]-a[0]*b[1])/q];}function ab(a){return Math.sqrt(a[0]*a[0]+a[1]*a[1]);}function two(Ma,Ka,Mb,Kb){var T=sb(Kb,C(w*w*Mb,0)),D=sb(ad(Ka,Kb),ad(C(w*w*Ma,0),dv(mu(Kb,Kb),T))),Xa=dv(mu(Ka,C(Y,0)),D);return [Xa,dv(mu(Kb,Xa),T)];}var top,base=C(Y,0);if(ds<2){var kk=ds==1?4*k:k,cc=ds==1?2*c:c,K=C(kk,w*cc);top=dv(mu(K,C(Y,0)),sb(K,C(w*w*m,0)));}else if(ds==2){var mu2=0.1,m2=mu2*m,f2=fn/(1+mu2),z2=Math.sqrt(3*mu2/(8*Math.pow(1+mu2,3))),k2=m2*Math.pow(2*Math.PI*f2,2),c2=2*z2*Math.sqrt(k2*m2);top=two(m,C(k,w*c),m2,C(k2,w*c2))[0];}else{var mb=0.5*m,kb=(m+mb)*Math.pow(2*Math.PI*0.7,2),cb=2*0.15*Math.sqrt(kb*(m+mb)),r=two(mb,C(kb,w*cb),m,C(k,w*c));top=r[1];base=r[0];}return 1000*ab(sb(top,base));})()" }] } },
  { id: "e2", book: "과학의 역사와 문화", page: 119, title: "용액 섞기로 감염 경로 역학 조사", purpose: "감염원 용액을 섞고 나누는 놀이로 감염을 퍼뜨린 뒤 지시약으로 확진자를 가리고 최초 감염자를 추적한다.",
    steps: ["역할을 정하고 번호를 붙인 컵에 같은 양의 물을 담는다", "한 컵에만 몰래 감염원(묽은 염기 용액)을 넣는다", "짝을 바꿔 가며 용액을 섞어 반씩 나누기를 세 번 한다", "지시약을 떨어뜨려 붉게 변한 컵(확진자)을 가린다", "접촉 기록으로 감염 경로와 최초 감염자를 찾는다"],
    iv: "접촉 차수(1~3차)", dv: "확진자 수(명)", cv: ["컵의 물 양", "감염원 농도·양", "섞고 나누는 방법"], safety: "수산화 나트륨은 피부·눈을 자극하므로 보안경과 장갑을 끼고, 페놀프탈레인 용액은 불 가까이 두지 않는다.",
    extend: ["접촉 차수만 4~5차로 늘리면 확진자 수가 어떻게 늘어날까", "섞지 않는 사람(거리 두기) 비율만 바꾸면 확진자 수가 얼마나 줄까", "참여 인원만 바꾸면?"],
    sim: { kind: "model", name: "가상 용액 섞기 놀이", noise: 0.02,
      note: "매 차수마다 섞는 사람끼리 무작위로 짝을 지어 두 컵을 섞고 반씩 나눕니다(홀수면 한 명은 쉼). 거리 두기 비율만큼의 사람은 처음부터 끝까지 섞지 않습니다. 지시약은 처음 감염원 농도의 1/1000까지 붉게 변한다고 가정해, 5차까지는 감염원이 조금이라도 섞인 컵은 모두 확진입니다. 평균은 같은 조건으로 300번 놀이한 값입니다.",
      inputs: [{ k: "r", label: "접촉 차수", unit: "차", min: 1, max: 5, step: 1, value: 3 },
               { k: "N", label: "참여 인원", unit: "명", min: 10, max: 30, step: 2, value: 20 },
               { k: "p", label: "섞지 않는 사람 비율", unit: "%", min: 0, max: 60, step: 10, value: 0 }],
      outputs: [{ k: "avg", label: "확진자 수(300번 평균)", unit: "명", dp: 1, expr: "(function(){function sh(z){for(var i=z.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),s=z[i];z[i]=z[j];z[j]=s;}}function run(){var a=[],mx=[],ids=[],i,j,t,q=Math.round(N*p/100),k=0;for(i=0;i<N;i++){a.push(i==0?1:0);ids.push(i);mx.push(true);}sh(ids);for(i=0;i<q;i++)mx[ids[i]]=false;for(t=0;t<r;t++){var g=[];for(i=0;i<N;i++)if(mx[i])g.push(i);sh(g);for(j=0;j+1<g.length;j+=2){var c=(a[g[j]]+a[g[j+1]])/2;a[g[j]]=c;a[g[j+1]]=c;}}for(i=0;i<N;i++)if(a[i]>0.001)k++;return k;}var S=0;for(var u=0;u<300;u++)S+=run();return S/300;})()" },
                { k: "one", label: "확진자 수(이번 한 번 놀이)", unit: "명", dp: 0, expr: "(function(){function sh(z){for(var i=z.length-1;i>0;i--){var j=Math.floor(Math.random()*(i+1)),s=z[i];z[i]=z[j];z[j]=s;}}var a=[],mx=[],ids=[],i,j,t,q=Math.round(N*p/100),k=0;for(i=0;i<N;i++){a.push(i==0?1:0);ids.push(i);mx.push(true);}sh(ids);for(i=0;i<q;i++)mx[ids[i]]=false;for(t=0;t<r;t++){var g=[];for(i=0;i<N;i++)if(mx[i])g.push(i);sh(g);for(j=0;j+1<g.length;j+=2){var c=(a[g[j]]+a[g[j+1]])/2;a[g[j]]=c;a[g[j+1]]=c;}}for(i=0;i<N;i++)if(a[i]>0.001)k++;return k;})()" }] } },
  { id: "e3", book: "과학의 역사와 문화", page: 133, title: "등하굣길 탄소 배출량과 미래 모빌리티", purpose: "교통수단별 탄소 배출 자료로 내 등하굣길 탄소 배출량을 계산하고 미래 교통을 생각한다.",
    steps: ["지도 앱으로 집에서 학교까지 거리를 잰다", "교통수단별 1 km당 배출 계수를 거리에 곱해 배출량을 계산한다", "친환경 자동차가 배출을 얼마나 줄이는지 토론한다", "바람직한 미래 모빌리티의 모습을 글로 쓴다"],
    iv: "교통수단 종류", dv: "하루(왕복) 탄소 배출량(g)", cv: ["같은 통학 거리", "같은 배출 계수 자료(g/km)"], safety: "",
    extend: ["통학 거리만 바꾸면 수단별 배출량 차이가 어떻게 달라질까", "자가용에 함께 타는 인원만 바꾸면 한 사람 몫 배출량이 버스보다 적어질 수 있을까"],
    sim: { kind: "model", name: "가상 통학 탄소 계산기", noise: 0.02,
      note: "하루 배출량 = 통학 거리 × 2(왕복) × 1 km당 1인 배출 계수. 가정한 계수: 도보·자전거 0, 버스 1인당 50 g/km(버스 한 대 약 1 kg/km를 승객 20명이 나눔), 휘발유 자가용 170 g/km, 전기차 70 g/km(1 km당 전기 0.15 kWh × 발전 배출 0.45 kg/kWh). 자가용·전기차는 함께 탄 인원으로 나눕니다. 한 해 = 등교일 190일.",
      choices: [{ k: "md", label: "교통수단", opts: [["도보", 0], ["자전거", 1], ["버스", 2], ["휘발유 자가용", 3], ["전기차", 4]], value: 2 }],
      inputs: [{ k: "d", label: "편도 통학 거리", unit: "km", min: 0.5, max: 15, step: 0.5, value: 3 },
               { k: "pp", label: "자가용에 함께 탄 인원", unit: "명", min: 1, max: 4, step: 1, value: 1 }],
      outputs: [{ k: "day", label: "하루(왕복) 배출량", unit: "g", dp: 0, expr: "(function(){var e=[0,0,50,170,70][md];if(md>=3)e=e/pp;return e*d*2;})()" },
                { k: "yr", label: "한 해 배출량", unit: "kg", dp: 1, expr: "(function(){var e=[0,0,50,170,70][md];if(md>=3)e=e/pp;return e*d*2*190/1000;})()" }] } }
] });
